import './globals.css'
import { Inter } from 'next/font/google'
import { ReduxProvider } from '@/redux/provider'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='min-h-screen bg-gradient-to-br from-blue-500
          text- to-blue-300'>
          <ReduxProvider>{children}</ReduxProvider>
          <Footer/>
        </div>
      </body>
    </html>
  )
}
